version: '3'

# volumes:
#   ./data/postgres:
#     driver: local

services:

  db:
    image: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASSWORD
    stdin_open: true
    tty: true

  demo_ts:
    depends_on:
      - db
    build: .
    volumes:
      - "./db/migrations:/usr/local/demo_ts/db/migrations"
    env_file:
    - .env
    restart: on-failure
    stdin_open: true
    tty: true
